import { emptyRecurring, isoDate } from './constants'
import { rangeFromSlots } from './time'
import type { Employer, Job, Recurring, Seeker, Slot, Weekday, Workplace } from './types'

function rec(partial: Partial<Recurring>): Recurring {
  return { ...emptyRecurring(), ...partial }
}

const w = (slots: Slot[]) => slots

export const SEEKERS: Seeker[] = [
  {
    id: 's-emma',
    name: 'Emma Peeters',
    city: 'Gent',
    hue: 18,
    bio: 'Verpleegkundige in shiften. Zoek extra flexi-werk in horeca of events op mijn vrije dagen — vooral overdag na een nachtshift.',
    sectors: ['Horeca', 'Events', 'Zorg'],
    skills: ['Bediening', 'Bar / tappen', 'Hostess / onthaal', 'Zorgondersteuning'],
    languages: ['Nederlands', 'Engels', 'Frans'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 4,
    hourlyRateMin: 14,
    lastMinute: true,
    rating: 4.9,
    jobsDone: 27,
    recurring: rec({
      tue: w(['namiddag', 'avond']),
      wed: w(['ochtend', 'namiddag']),
      fri: w(['avond']),
      sat: w(['flexibel']),
      sun: w(['ochtend', 'namiddag']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-yassin',
    name: 'Yassin El Amrani',
    city: 'Antwerpen',
    hue: 168,
    bio: 'Magazijnier met vroege shiften. Avonden en weekends vrij. Sterk in logistiek, picking en extra handen bij events.',
    sectors: ['Logistiek', 'Events', 'Retail'],
    skills: ['Magazijn', 'Picking', 'Eventopbouw', 'Chauffeur'],
    languages: ['Nederlands', 'Frans', 'Arabisch'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 6,
    hourlyRateMin: 15,
    lastMinute: true,
    rating: 4.8,
    jobsDone: 41,
    recurring: rec({
      mon: w(['avond']),
      tue: w(['avond']),
      wed: w(['avond']),
      thu: w(['avond']),
      sat: w(['ochtend', 'namiddag', 'avond']),
      sun: w(['flexibel']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-lore',
    name: 'Lore Vandenberghe',
    city: 'Leuven',
    hue: 42,
    bio: 'Werk in retail met wisselende uren. Ochtenden doordeweeks vaak vrij — ideaal voor administratie, kassa of onthaal.',
    sectors: ['Retail', 'Administratie', 'Horeca'],
    skills: ['Kassa', 'Administratie', 'Klantenservice', 'Bediening'],
    languages: ['Nederlands', 'Engels'],
    hasLicense: false,
    hasTransport: false,
    yearsExperience: 3,
    hourlyRateMin: 13,
    lastMinute: false,
    rating: 4.7,
    jobsDone: 18,
    recurring: rec({
      mon: w(['ochtend']),
      tue: w(['ochtend']),
      wed: w(['ochtend', 'namiddag']),
      thu: w(['ochtend']),
      sun: w(['namiddag', 'avond']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-thomas',
    name: 'Thomas De Smet',
    city: 'Gent',
    hue: 8,
    bio: 'Kok in een brasserie, maandag traditioneel dicht. Kan invallen in keuken of op events. Geen stress bij drukte.',
    sectors: ['Horeca', 'Events'],
    skills: ['Keuken', 'Bediening', 'Eventopbouw'],
    languages: ['Nederlands', 'Engels', 'Frans'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 8,
    hourlyRateMin: 16,
    lastMinute: true,
    rating: 4.9,
    jobsDone: 33,
    recurring: rec({
      mon: w(['flexibel']),
      tue: w(['ochtend']),
      sun: w(['avond']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-amira',
    name: 'Amira Benali',
    city: 'Brussel',
    hue: 280,
    bio: 'Student met een deeltijdse job. Namiddagen doordeweeks vrij. Zoek kassa, onthaal of administratie dichtbij.',
    sectors: ['Retail', 'Administratie', 'Events'],
    skills: ['Kassa', 'Hostess / onthaal', 'Administratie', 'Klantenservice'],
    languages: ['Nederlands', 'Frans', 'Engels', 'Arabisch'],
    hasLicense: false,
    hasTransport: false,
    yearsExperience: 2,
    hourlyRateMin: 13,
    lastMinute: false,
    rating: 4.6,
    jobsDone: 12,
    recurring: rec({
      mon: w(['namiddag']),
      tue: w(['namiddag']),
      wed: w(['namiddag']),
      thu: w(['namiddag']),
      fri: w(['namiddag']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-pieter',
    name: 'Pieter Janssens',
    city: 'Mechelen',
    hue: 200,
    bio: 'Productie in 2-ploegenstelsel. Wanneer ik vroege week heb, zijn avonden vrij — en omgekeerd. Last-minute oké.',
    sectors: ['Productie', 'Logistiek', 'Schoonmaak'],
    skills: ['Productie', 'Magazijn', 'Schoonmaak', 'Picking'],
    languages: ['Nederlands'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 5,
    hourlyRateMin: 14,
    lastMinute: true,
    rating: 4.5,
    jobsDone: 22,
    recurring: rec({
      mon: w(['avond']),
      wed: w(['avond']),
      fri: w(['ochtend', 'namiddag']),
      sat: w(['flexibel']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-sofie',
    name: 'Sofie Maes',
    city: 'Brugge',
    hue: 330,
    bio: 'Kantoor 9-to-5. Avonden en weekends vrij voor horeca of events. Betrouwbaar, vriendelijk, snel ingewerkt.',
    sectors: ['Horeca', 'Events', 'Retail'],
    skills: ['Bediening', 'Bar / tappen', 'Hostess / onthaal', 'Kassa'],
    languages: ['Nederlands', 'Engels', 'Frans'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 3,
    hourlyRateMin: 14,
    lastMinute: false,
    rating: 4.8,
    jobsDone: 19,
    recurring: rec({
      mon: w(['avond']),
      tue: w(['avond']),
      wed: w(['avond']),
      thu: w(['avond']),
      fri: w(['avond']),
      sat: w(['flexibel']),
      sun: w(['flexibel']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-noah',
    name: 'Noah Claes',
    city: 'Antwerpen',
    hue: 52,
    bio: 'Barkeeper met ervaring in festivals en privé-events. Zoek extra shiften naast mijn vaste weekendwerk.',
    sectors: ['Horeca', 'Events'],
    skills: ['Bar / tappen', 'Bediening', 'Eventopbouw', 'Hostess / onthaal'],
    languages: ['Nederlands', 'Engels'],
    hasLicense: false,
    hasTransport: true,
    yearsExperience: 5,
    hourlyRateMin: 15,
    lastMinute: true,
    rating: 4.9,
    jobsDone: 48,
    recurring: rec({
      mon: w(['flexibel']),
      tue: w(['avond']),
      wed: w(['avond']),
      thu: w(['namiddag', 'avond']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-fatima',
    name: 'Fatima Alami',
    city: 'Hasselt',
    hue: 145,
    bio: 'Zorgkundige. Weekends vaak vrij en extra shiften welkom in zorg, schoonmaak of keuken.',
    sectors: ['Zorg', 'Schoonmaak', 'Horeca'],
    skills: ['Zorgondersteuning', 'Schoonmaak', 'Keuken', 'Bediening'],
    languages: ['Nederlands', 'Frans', 'Arabisch'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 7,
    hourlyRateMin: 15,
    lastMinute: false,
    rating: 4.8,
    jobsDone: 15,
    recurring: rec({
      fri: w(['avond']),
      sat: w(['ochtend', 'namiddag', 'avond']),
      sun: w(['ochtend', 'namiddag']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-dries',
    name: 'Dries Coppens',
    city: 'Kortrijk',
    hue: 25,
    bio: 'Nachtdienst in logistiek. Overdag beschikbaar voor retail, magazijn of evenementen in West-Vlaanderen.',
    sectors: ['Logistiek', 'Retail', 'Events'],
    skills: ['Magazijn', 'Picking', 'Kassa', 'Eventopbouw'],
    languages: ['Nederlands', 'Engels'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 4,
    hourlyRateMin: 14,
    lastMinute: true,
    rating: 4.6,
    jobsDone: 21,
    recurring: rec({
      mon: w(['ochtend', 'namiddag']),
      tue: w(['ochtend', 'namiddag']),
      wed: w(['ochtend', 'namiddag']),
      thu: w(['ochtend', 'namiddag']),
      sun: w(['avond']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-julie',
    name: 'Julie Moens',
    city: 'Oostende',
    hue: 210,
    bio: 'Seizoenswerk aan de kust. Flexibel in horeca en events, ook last-minute als een collega uitvalt.',
    sectors: ['Horeca', 'Events', 'Schoonmaak'],
    skills: ['Bediening', 'Keuken', 'Schoonmaak', 'Bar / tappen'],
    languages: ['Nederlands', 'Frans', 'Engels'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 6,
    hourlyRateMin: 14,
    lastMinute: true,
    rating: 4.7,
    jobsDone: 36,
    recurring: rec({
      mon: w(['flexibel']),
      tue: w(['flexibel']),
      wed: w(['namiddag', 'avond']),
      thu: w(['avond']),
      sun: w(['ochtend']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
  {
    id: 's-kasper',
    name: 'Kasper Willems',
    city: 'Aalst',
    hue: 95,
    bio: 'Chauffeur en allrounder. Kan rijden, sjouwen, opbouwen. Ideaal als invaller voor een eenmalig event.',
    sectors: ['Events', 'Logistiek', 'Productie'],
    skills: ['Chauffeur', 'Eventopbouw', 'Magazijn', 'Productie'],
    languages: ['Nederlands', 'Engels'],
    hasLicense: true,
    hasTransport: true,
    yearsExperience: 9,
    hourlyRateMin: 16,
    lastMinute: true,
    rating: 4.8,
    jobsDone: 52,
    recurring: rec({
      tue: w(['flexibel']),
      wed: w(['flexibel']),
      thu: w(['avond']),
      sat: w(['ochtend', 'namiddag']),
      sun: w(['flexibel']),
    }),
    hours: {},
    overrides: {},
    blocked: [],
    onboardingDone: true,
  },
]

export const EMPLOYERS: Employer[] = [
  {
    id: 'e-kroon',
    company: 'Café De Kroon',
    contact: 'Annelies De Witte',
    city: 'Gent',
    sector: 'Horeca',
    hue: 18,
    onboardingDone: true,
    favorites: ['s-emma'],
  },
  {
    id: 'e-eventco',
    company: 'EventCo',
    contact: 'Bram Vercruysse',
    city: 'Antwerpen',
    sector: 'Events',
    hue: 200,
    onboardingDone: true,
    favorites: ['s-yassin'],
  },
  {
    id: 'e-martens',
    company: 'Superette Martens',
    contact: 'Karen Martens',
    city: 'Leuven',
    sector: 'Retail',
    hue: 42,
    onboardingDone: true,
    favorites: ['s-lore'],
  },
  {
    id: 'e-harbour',
    company: 'Hotel Harbour',
    contact: 'Pieter-Jan Lauwers',
    city: 'Brugge',
    sector: 'Horeca',
    hue: 210,
    onboardingDone: true,
    favorites: [],
  },
  {
    id: 'e-nord',
    company: 'Magazijn Nord',
    contact: 'Steven Goossens',
    city: 'Antwerpen',
    sector: 'Logistiek',
    hue: 168,
    onboardingDone: true,
    favorites: ['s-yassin'],
  },
]

const WP_KROON: Workplace = {
  address: 'Vrijdagmarkt 12',
  postal: '9000',
  city: 'Gent',
  lat: 51.0569,
  lng: 3.7254,
  access: 'Tram 1 of 4 tot Korenmarkt, daarna 4 min te voet. Fietsenstalling op de markt.',
  parking: 'Q-Park Voldersstraat, 3 min lopen. Beperkt straatparkeren rond de markt.',
  contactOnSite: 'Annelies De Witte — vraag naar haar aan de bar',
  notes: 'Ingang via de zijdeur naast de terraspoort. Zwarte kleding, schone schoenen.',
}

const WP_EVENTCO: Workplace = {
  address: 'Noorderlaan 88',
  postal: '2030',
  city: 'Antwerpen',
  lat: 51.2412,
  lng: 4.4091,
  access: 'Tram 6 tot Noorderlaan. Eigen vervoer is handig — 12 min vanaf Centraal.',
  parking: 'Gratis parking op het terrein, ingang via poort B.',
  contactOnSite: 'Bram Vercruysse — crew-ingang, gele hesjes liggen klaar',
  notes: 'Meld je 15 min vroeger. Veiligheidsschoenen verplicht, wij hebben extra paar.',
}

const WP_MARTENS: Workplace = {
  address: 'Bondgenotenlaan 45',
  postal: '3000',
  city: 'Leuven',
  lat: 50.8795,
  lng: 4.7011,
  access: '2 min van Leuven station, uitgang Bondgenotenlaan. Bushalte Martelarenplein.',
  parking: 'Geen winkelparking. Fietsenrek voor de deur. Q-Park Ladeuze op 6 min.',
  contactOnSite: 'Karen Martens — achteraan bij de kassa’s',
  notes: 'Personeelsingang via de zijsteeg (bel 12). Badge krijg je bij aankomst.',
}

const WP_HARBOUR: Workplace = {
  address: 'Spiegelrei 8',
  postal: '8000',
  city: 'Brugge',
  lat: 51.211,
  lng: 3.2265,
  access: '10 min te voet van Brugge station via Predikherenrei. Bus 4 tot Wollestraat.',
  parking: 'Hotelparking voor personeel, meld je aan de slagboom. Fietsenstalling in de koer.',
  contactOnSite: 'Pieter-Jan Lauwers — onthaal, vraag naar de duty manager',
  notes: 'Personeelsingang links van de hoofdingang. Donkere kleding, gesloten schoenen.',
}

const WP_NORD: Workplace = {
  address: 'Siberiastraat 14',
  postal: '2030',
  city: 'Antwerpen',
  lat: 51.2486,
  lng: 4.4072,
  access: 'Bus 760 tot Siberiastraat. Eigen wagen aangeraden buiten de spits.',
  parking: 'Grote parking voor het magazijn, inrijden via poort 2.',
  contactOnSite: 'Steven Goossens — kantoor naast de laadkade',
  notes: 'Meld je bij de portier. Veiligheidsschoenen en hesje verplicht (liggen klaar).',
}

const WP_FESTIVAL: Workplace = {
  address: 'Sint-Pietersplein 9',
  postal: '9000',
  city: 'Gent',
  lat: 51.0428,
  lng: 3.7272,
  access: 'Tram 1 tot Sint-Pietersstation, 8 min lopen. Crew-ingang aan de zuidzijde van het plein.',
  parking: 'Geen crew-parking op het plein. Drop-off aan de Kortrijksepoortstraat.',
  contactOnSite: 'Bram Vercruysse — crewtent, gele armband',
  notes: 'Neem ID mee. Oordoppen en water liggen in de crewtent. Zwarte kleding.',
}

export function seedJobs(): Job[] {
  const jobs: Array<Omit<Job, 'startTime' | 'endTime' | 'contractKind' | 'requiresLicense'>> = [
    {
      id: 'j-1',
      employerId: 'e-kroon',
      title: 'Bediening — collega ziek',
      company: 'Café De Kroon',
      city: 'Gent',
      date: isoDate(0),
      slots: ['avond'],
      skills: ['Bediening', 'Bar / tappen'],
      sector: 'Horeca',
      hourlyRate: 16,
      peopleNeeded: 1,
      urgent: true,
      description:
        'Onze avondshift zit zonder iemand. Drukke donderdag, terras + binnen. Ervaring met bediening is een plus, maar we werken je snel in.',
      status: 'open',
      workplace: WP_KROON,
    },
    {
      id: 'j-2',
      employerId: 'e-eventco',
      title: 'Opbouw privé-event',
      company: 'EventCo',
      city: 'Antwerpen',
      date: isoDate(2),
      slots: ['ochtend', 'namiddag'],
      skills: ['Eventopbouw', 'Magazijn'],
      sector: 'Events',
      hourlyRate: 17,
      peopleNeeded: 3,
      urgent: false,
      description:
        'Opbouw van een bedrijfsreceptie in een loods in Antwerpen-Noord. Tillen, zetten, afruimen. Eigen vervoer is handig.',
      status: 'open',
      workplace: WP_EVENTCO,
    },
    {
      id: 'j-3',
      employerId: 'e-martens',
      title: 'Kassa invaller',
      company: 'Superette Martens',
      city: 'Leuven',
      date: isoDate(1),
      slots: ['ochtend'],
      skills: ['Kassa', 'Klantenservice'],
      sector: 'Retail',
      hourlyRate: 14,
      peopleNeeded: 1,
      urgent: true,
      description:
        'Ochtendkassa. Iemand uitgevallen. Winkel in het centrum, vlotte klantenstroom.',
      status: 'open',
      workplace: WP_MARTENS,
    },
    {
      id: 'j-4',
      employerId: 'e-harbour',
      title: 'Breakfast & onthaal',
      company: 'Hotel Harbour',
      city: 'Brugge',
      date: isoDate(3),
      slots: ['ochtend'],
      skills: ['Hostess / onthaal', 'Bediening', 'Keuken'],
      sector: 'Horeca',
      hourlyRate: 15,
      peopleNeeded: 2,
      urgent: false,
      description:
        'Help bij het ontbijt buffet en onthaal van gasten. Glimlach verplicht, stressbestendigheid ook.',
      status: 'open',
      workplace: WP_HARBOUR,
    },
    {
      id: 'j-5',
      employerId: 'e-nord',
      title: 'Weekend picking',
      company: 'Magazijn Nord',
      city: 'Antwerpen',
      date: isoDate(3),
      slots: ['ochtend', 'namiddag'],
      skills: ['Picking', 'Magazijn'],
      sector: 'Logistiek',
      hourlyRate: 16,
      peopleNeeded: 4,
      urgent: false,
      description:
        'Extra handen in het weekend voor e-commerce orders. Ritme ligt hoog, sfeer is oké.',
      status: 'open',
      workplace: WP_NORD,
    },
    {
      id: 'j-6',
      employerId: 'e-kroon',
      title: 'Terras zaterdag',
      company: 'Café De Kroon',
      city: 'Gent',
      date: isoDate(2),
      slots: ['namiddag', 'avond'],
      skills: ['Bediening', 'Bar / tappen'],
      sector: 'Horeca',
      hourlyRate: 15,
      peopleNeeded: 2,
      urgent: false,
      description: 'Zonnige zaterdag verwacht. Terras + bar. We zoeken twee extra mensen.',
      status: 'open',
      workplace: WP_KROON,
    },
    {
      id: 'j-7',
      employerId: 'e-eventco',
      title: 'Festivalcrew bar',
      company: 'EventCo',
      city: 'Gent',
      date: isoDate(4),
      slots: ['flexibel'],
      skills: ['Bar / tappen', 'Bediening'],
      sector: 'Events',
      hourlyRate: 18,
      peopleNeeded: 6,
      urgent: false,
      description:
        'Kleine city-festivalbar. Shiften van 6u, start wanneer het jou past — ochtendopbouw of avondbar.',
      status: 'open',
      workplace: WP_FESTIVAL,
    },
    {
      id: 'j-8',
      employerId: 'e-harbour',
      title: 'Housekeeping piek',
      company: 'Hotel Harbour',
      city: 'Brugge',
      date: isoDate(5),
      slots: ['ochtend', 'namiddag'],
      skills: ['Schoonmaak'],
      sector: 'Schoonmaak',
      hourlyRate: 14,
      peopleNeeded: 2,
      urgent: false,
      description: 'Volzet weekend. Extra kamers poetsen in de voormiddag en namiddag.',
      status: 'open',
      workplace: WP_HARBOUR,
    },
    {
      id: 'j-9',
      employerId: 'e-martens',
      title: 'Avondvulling rekken',
      company: 'Superette Martens',
      city: 'Leuven',
      date: isoDate(0),
      slots: ['avond'],
      skills: ['Magazijn', 'Kassa'],
      sector: 'Retail',
      hourlyRate: 14,
      peopleNeeded: 1,
      urgent: true,
      description: 'Rekken vullen na sluiting. Rustig werk, klaar rond 21u.',
      status: 'open',
      workplace: WP_MARTENS,
    },
    {
      id: 'j-10',
      employerId: 'e-nord',
      title: 'Chauffeur korte ritten',
      company: 'Magazijn Nord',
      city: 'Antwerpen',
      date: isoDate(1),
      slots: ['namiddag'],
      skills: ['Chauffeur', 'Magazijn'],
      sector: 'Logistiek',
      hourlyRate: 18,
      peopleNeeded: 1,
      urgent: false,
      description: 'Bestelwagen, stadsritten Antwerpen. Rijbewijs B verplicht.',
      status: 'open',
      workplace: WP_NORD,
    },
  ]
  return jobs.map((j) => {
    const t = rangeFromSlots(j.slots)
    return {
      ...j,
      startTime: t.start,
      endTime: t.end,
      contractKind: j.sector === 'Events' || j.sector === 'Logistiek' ? 'extra' : 'flexi',
      requiresLicense: j.skills.includes('Chauffeur'),
    }
  })
}

export function weekdayFromIso(iso: string): Weekday {
  const d = new Date(iso + 'T12:00:00')
  const map = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'] as const
  return map[d.getDay()]
}
